spring:
  application:
    name: order
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/tenantDb
  #    username: postgres
  #    password: Grace@2002
  #  jpa:
  #    hibernate:
  #      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: gracelinjonax247@gmail.com
    password: kodo qaqr dsde hrgf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
tenants:
  datasource:
    tenantDb:
      url: jdbc:postgresql://localhost:5432/tenantDb
      username: postgres
      password: Grace@2002
      driverClassName: org.postgresql.Driver
    tenant_1:
      url: jdbc:postgresql://localhost:5432/tenant_1
      username: postgres
      password: Grace@2002
      driverClassName: org.postgresql.Driver
    tenant_2:
      url: jdbc:postgresql://localhost:5432/tenant_2
      username: postgres
      password: Grace@2002
      driverClassName: org.postgresql.Driver
#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: DEBUG

defaultTenant: tenantDb
